### ISSUE TITLE
Change Title

### ISSUE THREAD

**Issue by SalasD93** [Sirmaaalik/Project1#11]
IDK Honey, You Pick!

**Comment by SalasD93** [comment]
OR    IDK, You Pick!  to make it more applicable to a broader audience.....

**Comment by SalasD93** [comment]
Or IDK, You Pick!

**Comment by Sirmaaalik** [comment]
Do you guys have any other recommendations for the app name?? The target audience is hungry couples but if anyone comes up with another name, I am all ears.
